# This file is auto-generated by scanner.py

from primitives import *
from client_core import *


class WlDisplay(WLObject):
    EVENTS = ["error", "delete_id"]

    @request
    def sync(self, callback: NewID | int) -> bytes:
        return self.serialize_request(0, callback)

    @request
    def get_registry(self, registry: NewID | int) -> bytes:
        return self.serialize_request(1, registry)


class WlRegistry(WLObject):
    EVENTS = ["global", "global_remove"]

    @request
    def bind(self, name: UInt32 | int, id_: NewID | int) -> bytes:
        return self.serialize_request(0, name, id_)


class WlCallback(WLObject):
    EVENTS = ["done"]


class WlCompositor(WLObject):
    @request
    def create_surface(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def create_region(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)


class WlShmPool(WLObject):
    @request
    def create_buffer(
            self, id_: NewID | int, offset: Int32 | int, width: Int32 | int, height: Int32 | int, stride: Int32 | int,
            format_: UInt32 | int
    ) -> bytes:
        return self.serialize_request(0, id_, offset, width, height, stride, format_)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(1)

    @request
    def resize(self, size: Int32 | int) -> bytes:
        return self.serialize_request(2, size)


class WlShm(WLObject):
    EVENTS = ["format"]

    @request
    def create_pool(self, id_: NewID | int, fd: Fd | int, size: Int32 | int) -> bytes:
        return self.serialize_request(0, id_, fd, size)

    @request
    def release(self) -> bytes:
        return self.serialize_request(1)


class WlBuffer(WLObject):
    EVENTS = ["release"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)


class WlDataOffer(WLObject):
    EVENTS = ["offer", "source_actions", "action"]

    @request
    def accept(self, serial: UInt32 | int, mime_type: String | str) -> bytes:
        return self.serialize_request(0, serial, mime_type)

    @request
    def receive(self, mime_type: String | str, fd: Fd | int) -> bytes:
        return self.serialize_request(1, mime_type, fd)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(2)

    @request
    def finish(self) -> bytes:
        return self.serialize_request(3)

    @request
    def set_actions(self, dnd_actions: UInt32 | int, preferred_action: UInt32 | int) -> bytes:
        return self.serialize_request(4, dnd_actions, preferred_action)


class WlDataSource(WLObject):
    EVENTS = ["target", "send", "cancelled", "dnd_drop_performed", "dnd_finished", "action"]

    @request
    def offer(self, mime_type: String | str) -> bytes:
        return self.serialize_request(0, mime_type)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(1)

    @request
    def set_actions(self, dnd_actions: UInt32 | int) -> bytes:
        return self.serialize_request(2, dnd_actions)


class WlDataDevice(WLObject):
    EVENTS = ["data_offer", "enter", "leave", "motion", "drop", "selection"]

    @request
    def start_drag(self, source: ObjID | int, origin: ObjID | int, icon: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(0, source, origin, icon, serial)

    @request
    def set_selection(self, source: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, source, serial)

    @request
    def release(self) -> bytes:
        return self.serialize_request(2)


class WlDataDeviceManager(WLObject):
    @request
    def create_data_source(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def get_data_device(self, id_: NewID | int, seat: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, seat)


class WlShell(WLObject):
    @request
    def get_shell_surface(self, id_: NewID | int, surface: ObjID | int) -> bytes:
        return self.serialize_request(0, id_, surface)


class WlShellSurface(WLObject):
    EVENTS = ["ping", "configure", "popup_done"]

    @request
    def pong(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(0, serial)

    @request
    def move(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, seat, serial)

    @request
    def resize(self, seat: ObjID | int, serial: UInt32 | int, edges: UInt32 | int) -> bytes:
        return self.serialize_request(2, seat, serial, edges)

    @request
    def set_toplevel(self) -> bytes:
        return self.serialize_request(3)

    @request
    def set_transient(self, parent: ObjID | int, x: Int32 | int, y: Int32 | int, flags: UInt32 | int) -> bytes:
        return self.serialize_request(4, parent, x, y, flags)

    @request
    def set_fullscreen(self, method: UInt32 | int, framerate: UInt32 | int, output: ObjID | int) -> bytes:
        return self.serialize_request(5, method, framerate, output)

    @request
    def set_popup(
            self, seat: ObjID | int, serial: UInt32 | int, parent: ObjID | int, x: Int32 | int, y: Int32 | int,
            flags: UInt32 | int
    ) -> bytes:
        return self.serialize_request(6, seat, serial, parent, x, y, flags)

    @request
    def set_maximized(self, output: ObjID | int) -> bytes:
        return self.serialize_request(7, output)

    @request
    def set_title(self, title: String | str) -> bytes:
        return self.serialize_request(8, title)

    @request
    def set_class(self, class_: String | str) -> bytes:
        return self.serialize_request(9, class_)


class WlSurface(WLObject):
    EVENTS = ["enter", "leave", "preferred_buffer_scale", "preferred_buffer_transform"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def attach(self, buffer: ObjID | int, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(1, buffer, x, y)

    @request
    def damage(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)

    @request
    def frame(self, callback: NewID | int) -> bytes:
        return self.serialize_request(3, callback)

    @request
    def set_opaque_region(self, region: ObjID | int) -> bytes:
        return self.serialize_request(4, region)

    @request
    def set_input_region(self, region: ObjID | int) -> bytes:
        return self.serialize_request(5, region)

    @request
    def commit(self) -> bytes:
        return self.serialize_request(6)

    @request
    def set_buffer_transform(self, transform: Int32 | int) -> bytes:
        return self.serialize_request(7, transform)

    @request
    def set_buffer_scale(self, scale: Int32 | int) -> bytes:
        return self.serialize_request(8, scale)

    @request
    def damage_buffer(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(9, x, y, width, height)

    @request
    def offset(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(10, x, y)


class WlSeat(WLObject):
    EVENTS = ["capabilities", "name"]

    @request
    def get_pointer(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def get_keyboard(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_touch(self, id_: NewID | int) -> bytes:
        return self.serialize_request(2, id_)

    @request
    def release(self) -> bytes:
        return self.serialize_request(3)


class WlPointer(WLObject):
    EVENTS = [
        "enter", "leave", "motion", "button", "axis", "frame", "axis_source", "axis_stop", "axis_discrete",
        "axis_value120", "axis_relative_direction"
    ]

    @request
    def set_cursor(
            self, serial: UInt32 | int, surface: ObjID | int, hotspot_x: Int32 | int, hotspot_y: Int32 | int
    ) -> bytes:
        return self.serialize_request(0, serial, surface, hotspot_x, hotspot_y)

    @request
    def release(self) -> bytes:
        return self.serialize_request(1)


class WlKeyboard(WLObject):
    EVENTS = ["keymap", "enter", "leave", "key", "modifiers", "repeat_info"]

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlTouch(WLObject):
    EVENTS = ["down", "up", "motion", "frame", "cancel", "shape", "orientation"]

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlOutput(WLObject):
    EVENTS = ["geometry", "mode", "done", "scale", "name", "description"]

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlRegion(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def add(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(1, x, y, width, height)

    @request
    def subtract(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)


class WlSubcompositor(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_subsurface(self, id_: NewID | int, surface: ObjID | int, parent: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, surface, parent)


class WlSubsurface(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_position(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(1, x, y)

    @request
    def place_above(self, sibling: ObjID | int) -> bytes:
        return self.serialize_request(2, sibling)

    @request
    def place_below(self, sibling: ObjID | int) -> bytes:
        return self.serialize_request(3, sibling)

    @request
    def set_sync(self) -> bytes:
        return self.serialize_request(4)

    @request
    def set_desync(self) -> bytes:
        return self.serialize_request(5)


class WlFixes(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def destroy_registry(self, registry: ObjID | int) -> bytes:
        return self.serialize_request(1, registry)


class XdgWmBase(WLObject):
    EVENTS = ["ping"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def create_positioner(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_xdg_surface(self, id_: NewID | int, surface: ObjID | int) -> bytes:
        return self.serialize_request(2, id_, surface)

    @request
    def pong(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(3, serial)


class XdgPositioner(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(1, width, height)

    @request
    def set_anchor_rect(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)

    @request
    def set_anchor(self, anchor: UInt32 | int) -> bytes:
        return self.serialize_request(3, anchor)

    @request
    def set_gravity(self, gravity: UInt32 | int) -> bytes:
        return self.serialize_request(4, gravity)

    @request
    def set_constraint_adjustment(self, constraint_adjustment: UInt32 | int) -> bytes:
        return self.serialize_request(5, constraint_adjustment)

    @request
    def set_offset(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(6, x, y)

    @request
    def set_reactive(self) -> bytes:
        return self.serialize_request(7)

    @request
    def set_parent_size(self, parent_width: Int32 | int, parent_height: Int32 | int) -> bytes:
        return self.serialize_request(8, parent_width, parent_height)

    @request
    def set_parent_configure(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(9, serial)


class XdgSurface(WLObject):
    EVENTS = ["configure"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_toplevel(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_popup(self, id_: NewID | int, parent: ObjID | int, positioner: ObjID | int) -> bytes:
        return self.serialize_request(2, id_, parent, positioner)

    @request
    def set_window_geometry(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(3, x, y, width, height)

    @request
    def ack_configure(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(4, serial)


class XdgToplevel(WLObject):
    EVENTS = ["configure", "close", "configure_bounds", "wm_capabilities"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_parent(self, parent: ObjID | int) -> bytes:
        return self.serialize_request(1, parent)

    @request
    def set_title(self, title: String | str) -> bytes:
        return self.serialize_request(2, title)

    @request
    def set_app_id(self, app_id: String | str) -> bytes:
        return self.serialize_request(3, app_id)

    @request
    def show_window_menu(self, seat: ObjID | int, serial: UInt32 | int, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(4, seat, serial, x, y)

    @request
    def move(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(5, seat, serial)

    @request
    def resize(self, seat: ObjID | int, serial: UInt32 | int, edges: UInt32 | int) -> bytes:
        return self.serialize_request(6, seat, serial, edges)

    @request
    def set_max_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(7, width, height)

    @request
    def set_min_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(8, width, height)

    @request
    def set_maximized(self) -> bytes:
        return self.serialize_request(9)

    @request
    def unset_maximized(self) -> bytes:
        return self.serialize_request(10)

    @request
    def set_fullscreen(self, output: ObjID | int) -> bytes:
        return self.serialize_request(11, output)

    @request
    def unset_fullscreen(self) -> bytes:
        return self.serialize_request(12)

    @request
    def set_minimized(self) -> bytes:
        return self.serialize_request(13)


class XdgPopup(WLObject):
    EVENTS = ["configure", "popup_done", "repositioned"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def grab(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, seat, serial)

    @request
    def reposition(self, positioner: ObjID | int, token: UInt32 | int) -> bytes:
        return self.serialize_request(2, positioner, token)


class ZxdgDecorationManagerV1(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_toplevel_decoration(self, id_: NewID | int, toplevel: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, toplevel)


class ZxdgToplevelDecorationV1(WLObject):
    EVENTS = ["configure"]

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_mode(self, mode: UInt32 | int) -> bytes:
        return self.serialize_request(1, mode)

    @request
    def unset_mode(self) -> bytes:
        return self.serialize_request(2)
