# This file is auto-generated by scanner.py

from ..primitives import *
from ..client_core import *


class WlDisplay(WLObject):
    EVENTS = ["on_error", "on_delete_id"]

    def on_error(self, object_id: ObjID | int, code: UInt32 | int, message: String | str):
        raise NotImplementedError

    def on_delete_id(self, id_: UInt32 | int):
        raise NotImplementedError

    @request
    def sync(self, callback: NewID | int) -> bytes:
        return self.serialize_request(0, callback)

    @request
    def get_registry(self, registry: NewID | int) -> bytes:
        return self.serialize_request(1, registry)


class WlRegistry(WLObject):
    EVENTS = ["on_global", "on_global_remove"]

    def on_global(self, name: UInt32 | int, interface: String | str, version: UInt32 | int):
        raise NotImplementedError

    def on_global_remove(self, name: UInt32 | int):
        raise NotImplementedError

    @request
    def bind(self, name: UInt32 | int, id_: NewID | int) -> bytes:
        return self.serialize_request(0, name, id_)


class WlCallback(WLObject):
    EVENTS = ["on_done"]

    def on_done(self, callback_data: UInt32 | int):
        raise NotImplementedError


class WlCompositor(WLObject):
    @request
    def create_surface(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def create_region(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)


class WlShmPool(WLObject):
    @request
    def create_buffer(
            self, id_: NewID | int, offset: Int32 | int, width: Int32 | int, height: Int32 | int, stride: Int32 | int,
            format_: UInt32 | int
    ) -> bytes:
        return self.serialize_request(0, id_, offset, width, height, stride, format_)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(1)

    @request
    def resize(self, size: Int32 | int) -> bytes:
        return self.serialize_request(2, size)


class WlShm(WLObject):
    EVENTS = ["on_format"]

    def on_format(self, format_: UInt32 | int):
        raise NotImplementedError

    @request
    def create_pool(self, id_: NewID | int, fd: Fd | int, size: Int32 | int) -> bytes:
        return self.serialize_request(0, id_, fd, size)

    @request
    def release(self) -> bytes:
        return self.serialize_request(1)


class WlBuffer(WLObject):
    EVENTS = ["on_release"]

    def on_release(self):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)


class WlDataOffer(WLObject):
    EVENTS = ["on_offer", "on_source_actions", "on_action"]

    def on_offer(self, mime_type: String | str):
        raise NotImplementedError

    def on_source_actions(self, source_actions: UInt32 | int):
        raise NotImplementedError

    def on_action(self, dnd_action: UInt32 | int):
        raise NotImplementedError

    @request
    def accept(self, serial: UInt32 | int, mime_type: String | str) -> bytes:
        return self.serialize_request(0, serial, mime_type)

    @request
    def receive(self, mime_type: String | str, fd: Fd | int) -> bytes:
        return self.serialize_request(1, mime_type, fd)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(2)

    @request
    def finish(self) -> bytes:
        return self.serialize_request(3)

    @request
    def set_actions(self, dnd_actions: UInt32 | int, preferred_action: UInt32 | int) -> bytes:
        return self.serialize_request(4, dnd_actions, preferred_action)


class WlDataSource(WLObject):
    EVENTS = ["on_target", "on_send", "on_cancelled", "on_dnd_drop_performed", "on_dnd_finished", "on_action"]

    def on_target(self, mime_type: String | str):
        raise NotImplementedError

    def on_send(self, mime_type: String | str, fd: Fd | int):
        raise NotImplementedError

    def on_cancelled(self):
        raise NotImplementedError

    def on_dnd_drop_performed(self):
        raise NotImplementedError

    def on_dnd_finished(self):
        raise NotImplementedError

    def on_action(self, dnd_action: UInt32 | int):
        raise NotImplementedError

    @request
    def offer(self, mime_type: String | str) -> bytes:
        return self.serialize_request(0, mime_type)

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(1)

    @request
    def set_actions(self, dnd_actions: UInt32 | int) -> bytes:
        return self.serialize_request(2, dnd_actions)


class WlDataDevice(WLObject):
    EVENTS = ["on_data_offer", "on_enter", "on_leave", "on_motion", "on_drop", "on_selection"]

    def on_data_offer(self, id_: NewID | int):
        raise NotImplementedError

    def on_enter(
            self, serial: UInt32 | int, surface: ObjID | int, x: Fixed | float, y: Fixed | float, id_: ObjID | int
    ):
        raise NotImplementedError

    def on_leave(self):
        raise NotImplementedError

    def on_motion(self, time: UInt32 | int, x: Fixed | float, y: Fixed | float):
        raise NotImplementedError

    def on_drop(self):
        raise NotImplementedError

    def on_selection(self, id_: ObjID | int):
        raise NotImplementedError

    @request
    def start_drag(self, source: ObjID | int, origin: ObjID | int, icon: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(0, source, origin, icon, serial)

    @request
    def set_selection(self, source: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, source, serial)

    @request
    def release(self) -> bytes:
        return self.serialize_request(2)


class WlDataDeviceManager(WLObject):
    @request
    def create_data_source(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def get_data_device(self, id_: NewID | int, seat: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, seat)


class WlShell(WLObject):
    @request
    def get_shell_surface(self, id_: NewID | int, surface: ObjID | int) -> bytes:
        return self.serialize_request(0, id_, surface)


class WlShellSurface(WLObject):
    EVENTS = ["on_ping", "on_configure", "on_popup_done"]

    def on_ping(self, serial: UInt32 | int):
        raise NotImplementedError

    def on_configure(self, edges: UInt32 | int, width: Int32 | int, height: Int32 | int):
        raise NotImplementedError

    def on_popup_done(self):
        raise NotImplementedError

    @request
    def pong(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(0, serial)

    @request
    def move(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, seat, serial)

    @request
    def resize(self, seat: ObjID | int, serial: UInt32 | int, edges: UInt32 | int) -> bytes:
        return self.serialize_request(2, seat, serial, edges)

    @request
    def set_toplevel(self) -> bytes:
        return self.serialize_request(3)

    @request
    def set_transient(self, parent: ObjID | int, x: Int32 | int, y: Int32 | int, flags: UInt32 | int) -> bytes:
        return self.serialize_request(4, parent, x, y, flags)

    @request
    def set_fullscreen(self, method: UInt32 | int, framerate: UInt32 | int, output: ObjID | int) -> bytes:
        return self.serialize_request(5, method, framerate, output)

    @request
    def set_popup(
            self, seat: ObjID | int, serial: UInt32 | int, parent: ObjID | int, x: Int32 | int, y: Int32 | int,
            flags: UInt32 | int
    ) -> bytes:
        return self.serialize_request(6, seat, serial, parent, x, y, flags)

    @request
    def set_maximized(self, output: ObjID | int) -> bytes:
        return self.serialize_request(7, output)

    @request
    def set_title(self, title: String | str) -> bytes:
        return self.serialize_request(8, title)

    @request
    def set_class(self, class_: String | str) -> bytes:
        return self.serialize_request(9, class_)


class WlSurface(WLObject):
    EVENTS = ["on_enter", "on_leave", "on_preferred_buffer_scale", "on_preferred_buffer_transform"]

    def on_enter(self, output: ObjID | int):
        raise NotImplementedError

    def on_leave(self, output: ObjID | int):
        raise NotImplementedError

    def on_preferred_buffer_scale(self, factor: Int32 | int):
        raise NotImplementedError

    def on_preferred_buffer_transform(self, transform: UInt32 | int):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def attach(self, buffer: ObjID | int, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(1, buffer, x, y)

    @request
    def damage(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)

    @request
    def frame(self, callback: NewID | int) -> bytes:
        return self.serialize_request(3, callback)

    @request
    def set_opaque_region(self, region: ObjID | int) -> bytes:
        return self.serialize_request(4, region)

    @request
    def set_input_region(self, region: ObjID | int) -> bytes:
        return self.serialize_request(5, region)

    @request
    def commit(self) -> bytes:
        return self.serialize_request(6)

    @request
    def set_buffer_transform(self, transform: Int32 | int) -> bytes:
        return self.serialize_request(7, transform)

    @request
    def set_buffer_scale(self, scale: Int32 | int) -> bytes:
        return self.serialize_request(8, scale)

    @request
    def damage_buffer(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(9, x, y, width, height)

    @request
    def offset(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(10, x, y)


class WlSeat(WLObject):
    EVENTS = ["on_capabilities", "on_name"]

    def on_capabilities(self, capabilities: UInt32 | int):
        raise NotImplementedError

    def on_name(self, name: String | str):
        raise NotImplementedError

    @request
    def get_pointer(self, id_: NewID | int) -> bytes:
        return self.serialize_request(0, id_)

    @request
    def get_keyboard(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_touch(self, id_: NewID | int) -> bytes:
        return self.serialize_request(2, id_)

    @request
    def release(self) -> bytes:
        return self.serialize_request(3)


class WlPointer(WLObject):
    EVENTS = [
        "on_enter", "on_leave", "on_motion", "on_button", "on_axis", "on_frame", "on_axis_source", "on_axis_stop",
        "on_axis_discrete", "on_axis_value120", "on_axis_relative_direction"
    ]

    def on_enter(self, serial: UInt32 | int, surface: ObjID | int, surface_x: Fixed | float, surface_y: Fixed | float):
        raise NotImplementedError

    def on_leave(self, serial: UInt32 | int, surface: ObjID | int):
        raise NotImplementedError

    def on_motion(self, time: UInt32 | int, surface_x: Fixed | float, surface_y: Fixed | float):
        raise NotImplementedError

    def on_button(self, serial: UInt32 | int, time: UInt32 | int, button: UInt32 | int, state: UInt32 | int):
        raise NotImplementedError

    def on_axis(self, time: UInt32 | int, axis: UInt32 | int, value: Fixed | float):
        raise NotImplementedError

    def on_frame(self):
        raise NotImplementedError

    def on_axis_source(self, axis_source: UInt32 | int):
        raise NotImplementedError

    def on_axis_stop(self, time: UInt32 | int, axis: UInt32 | int):
        raise NotImplementedError

    def on_axis_discrete(self, axis: UInt32 | int, discrete: Int32 | int):
        raise NotImplementedError

    def on_axis_value120(self, axis: UInt32 | int, value120: Int32 | int):
        raise NotImplementedError

    def on_axis_relative_direction(self, axis: UInt32 | int, direction: UInt32 | int):
        raise NotImplementedError

    @request
    def set_cursor(
            self, serial: UInt32 | int, surface: ObjID | int, hotspot_x: Int32 | int, hotspot_y: Int32 | int
    ) -> bytes:
        return self.serialize_request(0, serial, surface, hotspot_x, hotspot_y)

    @request
    def release(self) -> bytes:
        return self.serialize_request(1)


class WlKeyboard(WLObject):
    EVENTS = ["on_keymap", "on_enter", "on_leave", "on_key", "on_modifiers", "on_repeat_info"]

    def on_keymap(self, format_: UInt32 | int, fd: Fd | int, size: UInt32 | int):
        raise NotImplementedError

    def on_enter(self, serial: UInt32 | int, surface: ObjID | int, keys: Array | int):
        raise NotImplementedError

    def on_leave(self, serial: UInt32 | int, surface: ObjID | int):
        raise NotImplementedError

    def on_key(self, serial: UInt32 | int, time: UInt32 | int, key: UInt32 | int, state: UInt32 | int):
        raise NotImplementedError

    def on_modifiers(
            self, serial: UInt32 | int, mods_depressed: UInt32 | int, mods_latched: UInt32 | int,
            mods_locked: UInt32 | int, group: UInt32 | int
    ):
        raise NotImplementedError

    def on_repeat_info(self, rate: Int32 | int, delay: Int32 | int):
        raise NotImplementedError

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlTouch(WLObject):
    EVENTS = ["on_down", "on_up", "on_motion", "on_frame", "on_cancel", "on_shape", "on_orientation"]

    def on_down(
            self, serial: UInt32 | int, time: UInt32 | int, surface: ObjID | int, id_: Int32 | int, x: Fixed | float,
            y: Fixed | float
    ):
        raise NotImplementedError

    def on_up(self, serial: UInt32 | int, time: UInt32 | int, id_: Int32 | int):
        raise NotImplementedError

    def on_motion(self, time: UInt32 | int, id_: Int32 | int, x: Fixed | float, y: Fixed | float):
        raise NotImplementedError

    def on_frame(self):
        raise NotImplementedError

    def on_cancel(self):
        raise NotImplementedError

    def on_shape(self, id_: Int32 | int, major: Fixed | float, minor: Fixed | float):
        raise NotImplementedError

    def on_orientation(self, id_: Int32 | int, orientation: Fixed | float):
        raise NotImplementedError

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlOutput(WLObject):
    EVENTS = ["on_geometry", "on_mode", "on_done", "on_scale", "on_name", "on_description"]

    def on_geometry(
            self, x: Int32 | int, y: Int32 | int, physical_width: Int32 | int, physical_height: Int32 | int,
            subpixel: Int32 | int, make: String | str, model: String | str, transform: Int32 | int
    ):
        raise NotImplementedError

    def on_mode(self, flags: UInt32 | int, width: Int32 | int, height: Int32 | int, refresh: Int32 | int):
        raise NotImplementedError

    def on_done(self):
        raise NotImplementedError

    def on_scale(self, factor: Int32 | int):
        raise NotImplementedError

    def on_name(self, name: String | str):
        raise NotImplementedError

    def on_description(self, description: String | str):
        raise NotImplementedError

    @request
    def release(self) -> bytes:
        return self.serialize_request(0)


class WlRegion(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def add(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(1, x, y, width, height)

    @request
    def subtract(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)


class WlSubcompositor(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_subsurface(self, id_: NewID | int, surface: ObjID | int, parent: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, surface, parent)


class WlSubsurface(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_position(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(1, x, y)

    @request
    def place_above(self, sibling: ObjID | int) -> bytes:
        return self.serialize_request(2, sibling)

    @request
    def place_below(self, sibling: ObjID | int) -> bytes:
        return self.serialize_request(3, sibling)

    @request
    def set_sync(self) -> bytes:
        return self.serialize_request(4)

    @request
    def set_desync(self) -> bytes:
        return self.serialize_request(5)


class WlFixes(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def destroy_registry(self, registry: ObjID | int) -> bytes:
        return self.serialize_request(1, registry)
