# This file is auto-generated by scanner.py

from ..primitives import *
from ..client_core import *


class XdgWmBase(WLObject):
    EVENTS = ["on_ping"]

    def on_ping(self, serial: UInt32 | int):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def create_positioner(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_xdg_surface(self, id_: NewID | int, surface: ObjID | int) -> bytes:
        return self.serialize_request(2, id_, surface)

    @request
    def pong(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(3, serial)


class XdgPositioner(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(1, width, height)

    @request
    def set_anchor_rect(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(2, x, y, width, height)

    @request
    def set_anchor(self, anchor: UInt32 | int) -> bytes:
        return self.serialize_request(3, anchor)

    @request
    def set_gravity(self, gravity: UInt32 | int) -> bytes:
        return self.serialize_request(4, gravity)

    @request
    def set_constraint_adjustment(self, constraint_adjustment: UInt32 | int) -> bytes:
        return self.serialize_request(5, constraint_adjustment)

    @request
    def set_offset(self, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(6, x, y)

    @request
    def set_reactive(self) -> bytes:
        return self.serialize_request(7)

    @request
    def set_parent_size(self, parent_width: Int32 | int, parent_height: Int32 | int) -> bytes:
        return self.serialize_request(8, parent_width, parent_height)

    @request
    def set_parent_configure(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(9, serial)


class XdgSurface(WLObject):
    EVENTS = ["on_configure"]

    def on_configure(self, serial: UInt32 | int):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_toplevel(self, id_: NewID | int) -> bytes:
        return self.serialize_request(1, id_)

    @request
    def get_popup(self, id_: NewID | int, parent: ObjID | int, positioner: ObjID | int) -> bytes:
        return self.serialize_request(2, id_, parent, positioner)

    @request
    def set_window_geometry(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(3, x, y, width, height)

    @request
    def ack_configure(self, serial: UInt32 | int) -> bytes:
        return self.serialize_request(4, serial)


class XdgToplevel(WLObject):
    EVENTS = ["on_configure", "on_close", "on_configure_bounds", "on_wm_capabilities"]

    def on_configure(self, width: Int32 | int, height: Int32 | int, states: Array | int):
        raise NotImplementedError

    def on_close(self):
        raise NotImplementedError

    def on_configure_bounds(self, width: Int32 | int, height: Int32 | int):
        raise NotImplementedError

    def on_wm_capabilities(self, capabilities: Array | int):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_parent(self, parent: ObjID | int) -> bytes:
        return self.serialize_request(1, parent)

    @request
    def set_title(self, title: String | str) -> bytes:
        return self.serialize_request(2, title)

    @request
    def set_app_id(self, app_id: String | str) -> bytes:
        return self.serialize_request(3, app_id)

    @request
    def show_window_menu(self, seat: ObjID | int, serial: UInt32 | int, x: Int32 | int, y: Int32 | int) -> bytes:
        return self.serialize_request(4, seat, serial, x, y)

    @request
    def move(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(5, seat, serial)

    @request
    def resize(self, seat: ObjID | int, serial: UInt32 | int, edges: UInt32 | int) -> bytes:
        return self.serialize_request(6, seat, serial, edges)

    @request
    def set_max_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(7, width, height)

    @request
    def set_min_size(self, width: Int32 | int, height: Int32 | int) -> bytes:
        return self.serialize_request(8, width, height)

    @request
    def set_maximized(self) -> bytes:
        return self.serialize_request(9)

    @request
    def unset_maximized(self) -> bytes:
        return self.serialize_request(10)

    @request
    def set_fullscreen(self, output: ObjID | int) -> bytes:
        return self.serialize_request(11, output)

    @request
    def unset_fullscreen(self) -> bytes:
        return self.serialize_request(12)

    @request
    def set_minimized(self) -> bytes:
        return self.serialize_request(13)


class XdgPopup(WLObject):
    EVENTS = ["on_configure", "on_popup_done", "on_repositioned"]

    def on_configure(self, x: Int32 | int, y: Int32 | int, width: Int32 | int, height: Int32 | int):
        raise NotImplementedError

    def on_popup_done(self):
        raise NotImplementedError

    def on_repositioned(self, token: UInt32 | int):
        raise NotImplementedError

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def grab(self, seat: ObjID | int, serial: UInt32 | int) -> bytes:
        return self.serialize_request(1, seat, serial)

    @request
    def reposition(self, positioner: ObjID | int, token: UInt32 | int) -> bytes:
        return self.serialize_request(2, positioner, token)
