# This file is auto-generated by scanner.py

from ..primitives import *
from ..client_core import *


class ZxdgDecorationManagerV1(WLObject):
    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def get_toplevel_decoration(self, id_: NewID | int, toplevel: ObjID | int) -> bytes:
        return self.serialize_request(1, id_, toplevel)


class ZxdgToplevelDecorationV1(WLObject):
    EVENTS = ["on_configure"]

    def on_configure(self, mode: UInt32 | int):
        raise NotImplementedError(
            f"'{type(self).__name__}' does not implement callback for event 'zxdg_toplevel_decoration_v1::configure'"
        )

    @request
    def destroy(self) -> bytes:
        return self.serialize_request(0)

    @request
    def set_mode(self, mode: UInt32 | int) -> bytes:
        return self.serialize_request(1, mode)

    @request
    def unset_mode(self) -> bytes:
        return self.serialize_request(2)
